### ISSUE TITLE
Getting SSL handshake error while running download code task, 405 error for create PR task.

### ISSUE THREAD

**Issue by ryadav-xebia** [xebialabs-community/xlr-bitbucket-plugin#8]
Using XL Release 8.5.0 and getting the below error on Download Code task.

2320587fb5f4023a6f1570274860a89/Task052810c824404393b588c603d49c4ce8} WARN  c.x.x.s.jython.JythonScriptService - Exception during execution
javax.script.ScriptException: requests.exceptions.SSLError: [Errno 1] certificate verify failed (javax.net.ssl.SSLHandshakeException: General SSLEngine problem) in <script> at line number 16
        at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:222)
        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:59)
        at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
        at com.xebialabs.xlrelease.script.Jsr223ScriptExecutor.lambda$doPrivileged$0(Jsr223ScriptExecutor.java:69)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.xebialabs.xlrelease.script.Jsr223ScriptExecutor.doPrivileged(Jsr223ScriptExecutor.java:69)
        at com.xebialabs.xlrelease.script.jython.JythonScriptExecutor.evalScriptPrivileged(JythonScriptExecutor.java:63)
        at com.xebialabs.xlrelease.script.jython.JythonScriptExecutor.evalScriptWithUtilities(JythonScriptExecutor.java:75)
        at com.xebialabs.xlrelease.script.jython.JythonScriptExecutor.evalScriptWithApi(JythonScriptExecutor.java:52)
        at com.xebialabs.xlrelease.script.DefaultScriptService.executeScript(DefaultScriptService.java:789)
        at com.xebialabs.xlrelease.script.DefaultScriptService.lambda$executeCustomScriptTask$1(DefaultScriptService.java:217)
        at com.xebialabs.deployit.plumbing.scheduler.Scheduler.lambda$withLoggedExceptions$0(Scheduler.java:69)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Getting 405 error , while using Create PR task.

HTTP Status [405] – [Method Not Allowed]</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The method received in the request-line is known by the origin server but not supported by the target resource

The certificates are imported into the XLR trust store and the Test Connection works just fine.

**Comment by anisbenali** [comment]
+1
